sigma: 0.35
regularization_param: 0.0004

system:
  system_id: "PlanarQuadrotorEnv-v0"

  sampling_time: 0.1

  action_space:
    lower_bound: [10, 10]
    upper_bound: [40, 40]

sample:
  sample_space:
    sample_scheme: "uniform"
    lower_bound: [-1.2, -1, -2.5, -5, -6.283185307179586, -5]
    upper_bound: [1.2, 1, 2.5, 5, 6.283185307179586, 5]
    sample_size: 2500

  action_space:
    sample_scheme: "grid"
    lower_bound: [10, 10]
    upper_bound: [40, 40]
    grid_resolution: [20, 20]

simulation:
  initial_condition: [0, 0, 0.5, 0, 0, 0]

plot_cfg:
  plot_dims: [0, 2]