name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.2.0
  - nbsphinx==0.8.1
  - pip:
    - ipykernel
    - jupytext
    - furo
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - sphinx-inline-tabs
    - sphinxcontrib-bibtex